// Generated by tools/build.py.
export const HUB = {
 "name": "UGBA 101A Study Hub",
 "short": "UGBA 101A",
 "slug": "ugba101a",
 "mode": "shared-web",
 "focus": {
  "label": "Mock-exam focus",
  "short": "Mock",
  "blurb": "What the prof's Fall 2026 mock exam tests, ranked by how likely it is on Midterm 1 (the real exam is the same format, just longer). Start at the top."
 }
};
